name: CI

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          runtime: node@24
          install: false
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build